// 更新路由方向
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION'
export const UPDATE_LOADING = 'UPDATE_LOADING'
export const BUTTON_LOADING = 'BUTTON_LOADING'
export const LEAVE_REMIND = 'LEAVE_REMIND'
export const ROUTER_KEY = 'ROUTER_KEY'
export const SET_USER_INFO = 'SET_USER_INFO'
export const GET_NOTICE_LIST = 'GET_NOTICE_LIST'

export const GET_GOODS_LIST = 'GET_GOODS_LIST'
export const SET_GOODS_CAR = 'SET_GOODS_CAR'
export const CLEAR_CAR = 'CLEAR_CAR'
export const REMOVE_GOODS = 'REMOVE_GOODS'